### ISSUE TITLE
What is the purpose of the OPERA radar archive database?

### ISSUE THREAD

**Issue by peterdesmet** [aloftdata/registry#13]
I noticed on the [opera map](https://www.eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/index.html) that OPERA also has an `RADAR ARCHIVE` ([raw file](https://www.eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/OPERA_RADARS_ARH_DB.json)). Some of the radars have a number identical to the `RADARS` database.

The main difference seems to be that these radars have a new property `finishyear` and a status `0`, with the exception of `skjav` and `skkoj` (also appearing in `RADARS`) that have status `1` and an invalid `finishyear`.

@leijnse I assume the purpose of this file is to track historical radars? If so, can we suggest to merge this information with the `RADARS` database/file: it already contains 39 radars with `"status": "0"` and would make for a single reference.

**Comment by leijnse** [comment]
You're right about the purpose of the radar archive. I will discuss the option of merging the two databases at the OPERA meeting in 1.5 weeks.

**Comment by peterdesmet** [comment]
@leijnse @BarVodSur I'd like to pick up this issue again. It would be great if both files could be merged and all radars have a `finishyear` property (that is empty for active radars). It would also be good to have a `replacedby` property, to link replacements of radars or radar codes.

**Comment by peterdesmet** [comment]
Although a single file would be better in my opinion (with e.g. different numbers assigned to radars that got replaced but didn't change their `odimcode` like `deeis`), we can currently deal with 2 files. Those are merged in this script (https://github.com/enram/aloftdata.eu/blob/main/_data/OPERA_RADARS_DB.R) to create a single list at https://aloftdata.eu/radars/

**Comment by BarVodSur** [comment]
Dear Peter,

 

Yes, we are tracking old radars, but we can’t have them in the same database because they have the same number an new ones but different characteristics. As I wrote before, status means it doesn’t send the data to OPERA. 

 

Country representatives in OPERA are giving us the info about their radars. 

 

BR,

Barbara 

 

 



 

From: Peter Desmet ***@***.***> 
Sent: Wednesday, November 13, 2024 10:39 AM
To: enram/registry ***@***.***>
Cc: Barbara Vodaric Surija ***@***.***>; Assign ***@***.***>
Subject: [enram/registry] What is the purpose of the OPERA radar archive database? (#13)

 

I noticed on the opera map <https://www.eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/index.html>  that OPERA also has an RADAR ARCHIVE (raw file <https://www.eumetnet.eu/wp-content/themes/aeron-child/observations-programme/current-activities/opera/database/OPERA_Database/OPERA_RADARS_ARH_DB.json> ). Some of the radars have a number identical to the RADARS database.

The main difference seems to be that these radars have a new property finishyear and a status 0, with the exception of skjav and skkoj (also appearing in RADARS) that have status 1 and an invalid finishyear.

@leijnse <https://github.com/leijnse>  I assume the purpose of this file is to track historical radars? If so, can we suggest to merge this information with the RADARS database/file: it already contains 39 radars with "status": "0" and would make for a single reference.
